#!/usr/bin/env bash
notes ls -ro |
    tail -n +2 |
    fzf --delimiter="\t" \
        --preview="bat --color=always $NOTES_CLI_HOME/{1}" \
        --preview-window=up:60% |
    awk -F'\t' '{print $1}' |
    xargs -I{} $EDITOR "$NOTES_CLI_HOME/{}"
